
#ifndef _C1_an1_
#define _C1_an1_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_REFERENCE F1_4(EIF_REFERENCE);
extern EIF_REFERENCE F1_5(EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_8(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_9(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);
extern void F1_15(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_23(EIF_REFERENCE);
RTOSHF (EIF_REFERENCE,24)
static EIF_REFERENCE F1_24_body(EIF_REFERENCE);
extern EIF_REFERENCE F1_24(EIF_REFERENCE);
extern EIF_REFERENCE F1_25(EIF_REFERENCE);
extern EIF_REFERENCE F1_26(EIF_REFERENCE);
extern void F1_27(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_29(EIF_REFERENCE);
extern void F1_30(EIF_REFERENCE);
extern void F1_31(EIF_REFERENCE);
extern EIF_POINTER F1_33(EIF_REFERENCE);
extern void EIF_Minit1(void);
extern void F116_3290(EIF_REFERENCE, EIF_REFERENCE);
extern void F921_10332(EIF_REFERENCE, EIF_REFERENCE);
extern void F28_925(EIF_REFERENCE, EIF_REFERENCE);
extern void F923_10435(EIF_REFERENCE, EIF_REFERENCE);
extern void F28_922(EIF_REFERENCE);
extern char *(*R6917[])();
extern char *(*R28[])();
extern char *(*R5315[])();

#ifdef __cplusplus
}
#endif

#endif
