/*
 * Generated by ISE 14.05.9.5417 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F484_10330();
extern void F486_10483();
extern void F492_10552();
extern void F493_10691();
extern void F959_6236();
extern void F948_9713();
extern void F138_3068();
extern EIF_REFERENCE F138_3055();
extern EIF_BOOLEAN F138_3067();
extern EIF_BOOLEAN F138_3072();
extern void F138_3077();
extern void F138_3078();
extern void F138_3079();
extern void F122_2871();
extern EIF_TYPED_VALUE F122_2872();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F484_10330;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F492_10552;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F959_6236;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F486_10483;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F493_10691;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F948_9713;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F138_3068;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_3067;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F138_3055;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_3072;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F138_3077;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F138_3078;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F138_3079;

	egc_str_dtype = 485;

	egc_str32_dtype = 492;
	egc_arr_dtype = 958;
	egc_tup_dtype = 414;
	egc_disp_rout_id = 5925;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)1227;
	egc_sp_wchar = (EIF_TYPE_INDEX)1402;
	egc_sp_bool = (EIF_TYPE_INDEX)1304;
	egc_sp_uint8 = (EIF_TYPE_INDEX)1036;
	egc_sp_uint16 = (EIF_TYPE_INDEX)1329;
	egc_sp_uint32 = (EIF_TYPE_INDEX)1144;
	egc_sp_uint64 = (EIF_TYPE_INDEX)1256;
	egc_sp_int8 = (EIF_TYPE_INDEX)1000;
	egc_sp_int16 = (EIF_TYPE_INDEX)1544;
	egc_sp_int32 = (EIF_TYPE_INDEX)1078;
	egc_sp_int64 = (EIF_TYPE_INDEX)1513;
	egc_sp_real32 = (EIF_TYPE_INDEX)1474;
	egc_sp_real64 = (EIF_TYPE_INDEX)1172;
	egc_sp_pointer = (EIF_TYPE_INDEX)1114;
	egc_sp_ref = (EIF_TYPE_INDEX)945;

	egc_uint8_dtype = 437;
	egc_uint16_dtype = 443;
	egc_uint32_dtype = 440;
	egc_uint64_dtype = 452;
	egc_int8_dtype = 416;
	egc_int16_dtype = 449;
	egc_int32_dtype = 446;
	egc_int64_dtype = 428;
	egc_bool_dtype = 431;
	egc_real32_dtype = 419;
	egc_char_dtype = 425;
	egc_wchar_dtype = 422;
	egc_real64_dtype = 434;
	egc_point_dtype = 455;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 163;
	egc_except_emnger_dtype = 137;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "spaceling";
	egc_system_location = "/Users/HB_Y/Documents/Eiffel-Projects/MVC_Spaceling/EIFGENs/application/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1447385492;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 1598;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 13400;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 121;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F122_2871;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F122_2872;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 1597; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
