/*
 * Generated by ISE 14.05.9.5417 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F219_6236();
extern void F221_6389();
extern void F226_6458();
extern void F227_6597();
extern void F246_3531();
extern void F242_6117();
extern void F51_1182();
extern EIF_REFERENCE F51_1169();
extern EIF_BOOLEAN F51_1181();
extern EIF_BOOLEAN F51_1186();
extern void F51_1191();
extern void F51_1192();
extern void F51_1193();
extern void F44_1096();
extern EIF_TYPED_VALUE F44_1097();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F219_6236;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F226_6458;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F246_3531;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F221_6389;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F227_6597;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F242_6117;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F51_1182;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1181;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F51_1169;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1186;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1191;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F51_1192;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F51_1193;

	egc_str_dtype = 220;

	egc_str32_dtype = 226;
	egc_arr_dtype = 245;
	egc_tup_dtype = 174;
	egc_disp_rout_id = 2685;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)568;
	egc_sp_wchar = (EIF_TYPE_INDEX)804;
	egc_sp_bool = (EIF_TYPE_INDEX)439;
	egc_sp_uint8 = (EIF_TYPE_INDEX)639;
	egc_sp_uint16 = (EIF_TYPE_INDEX)587;
	egc_sp_uint32 = (EIF_TYPE_INDEX)538;
	egc_sp_uint64 = (EIF_TYPE_INDEX)484;
	egc_sp_int8 = (EIF_TYPE_INDEX)747;
	egc_sp_int16 = (EIF_TYPE_INDEX)713;
	egc_sp_int32 = (EIF_TYPE_INDEX)357;
	egc_sp_int64 = (EIF_TYPE_INDEX)668;
	egc_sp_real32 = (EIF_TYPE_INDEX)823;
	egc_sp_real64 = (EIF_TYPE_INDEX)383;
	egc_sp_pointer = (EIF_TYPE_INDEX)308;
	egc_sp_ref = (EIF_TYPE_INDEX)260;

	egc_uint8_dtype = 197;
	egc_uint16_dtype = 203;
	egc_uint32_dtype = 200;
	egc_uint64_dtype = 212;
	egc_int8_dtype = 176;
	egc_int16_dtype = 209;
	egc_int32_dtype = 206;
	egc_int64_dtype = 188;
	egc_bool_dtype = 191;
	egc_real32_dtype = 179;
	egc_char_dtype = 185;
	egc_wchar_dtype = 182;
	egc_real64_dtype = 194;
	egc_point_dtype = 215;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 62;
	egc_except_emnger_dtype = 50;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "tool_rental";
	egc_system_location = "/Users/HB_Y/Documents/Eiffel-Projects/report3/tool_rental/EIFGENs/tool_rental_soln/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1442027670;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 895;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "OWNER.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 4980;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 43;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F44_1096;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F44_1097;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 865; /* OWNER */
	}
}

#ifdef __cplusplus
}
#endif
